export function renderSqlServerInsertScript(dataset) {
  const chunks = [
    "-- Generated by sql-seed-mvp",
    "-- Review before running against any database.",
    "SET XACT_ABORT ON;",
    "BEGIN TRANSACTION;"
  ];

  // Disable foreign key checks temporarily for all tables being seeded
  for (const table of dataset.tables) {
    if (table.rows.length === 0) continue;
    const qualifiedName = `[${table.schema}].[${table.name}]`;
    chunks.push(`ALTER TABLE ${qualifiedName} NOCHECK CONSTRAINT ALL;`);
  }

  // Insert records
  for (const table of dataset.tables) {
    if (table.rows.length === 0) continue;
    const writableColumns = table.columns.filter((column) => !column.computed);
    const identityColumns = writableColumns.filter((column) => column.identity);
    const qualifiedName = `[${table.schema}].[${table.name}]`;

    chunks.push("");
    chunks.push(`-- ${qualifiedName}`);
    if (identityColumns.length > 0) chunks.push(`SET IDENTITY_INSERT ${qualifiedName} ON;`);

    for (const row of table.rows) {
      const columnList = writableColumns.map((column) => `[${column.name}]`).join(", ");
      const values = writableColumns.map((column) => sqlLiteral(row[column.name])).join(", ");
      chunks.push(`INSERT INTO ${qualifiedName} (${columnList}) VALUES (${values});`);
    }

    if (identityColumns.length > 0) chunks.push(`SET IDENTITY_INSERT ${qualifiedName} OFF;`);
  }

  // Re-enable and validate all constraints on transaction complete
  chunks.push("");
  for (const table of dataset.tables) {
    if (table.rows.length === 0) continue;
    const qualifiedName = `[${table.schema}].[${table.name}]`;
    chunks.push(`ALTER TABLE ${qualifiedName} WITH CHECK CHECK CONSTRAINT ALL;`);
  }

  chunks.push("");
  chunks.push("COMMIT TRANSACTION;");
  chunks.push("");
  return chunks.join("\n");
}

export function renderCsvFiles(dataset) {
  return dataset.tables.map((table) => {
    const columns = table.columns.filter((column) => !column.computed);
    const lines = [
      columns.map((column) => csvCell(column.name)).join(","),
      ...table.rows.map((row) => columns.map((column) => csvCell(row[column.name])).join(","))
    ];
    return {
      name: `${table.schema}.${table.name}.csv`,
      content: `${lines.join("\n")}\n`
    };
  });
}

function sqlLiteral(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  return `N'${String(value).replaceAll("'", "''")}'`;
}

function csvCell(value) {
  if (value === null || value === undefined) return "";
  const text = String(value);
  if (/[",\n\r]/.test(text)) return `"${text.replaceAll('"', '""')}"`;
  return text;
}
